/**
 * @description       : 
 * @author            : Mayank Singh
 * @group             : 
 * @last modified on  : 05-16-2024
 * @last modified by  : Mayank Singh
**/
public class CoordinatesWrapper {
    public String latitude;
    public String longitude;
    
    public CoordinatesWrapper(String latitude, String longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }
}